gazebo_ros_control:
  pid_gains:
    left_main_wheel_joint:  {p: 6.0,  i: 0.0, d: 0.2, i_clamp_min: -0.1, i_clamp_max: 0.1}
    right_main_wheel_joint: {p: 6.0,  i: 0.0, d: 0.2, i_clamp_min: -0.1, i_clamp_max: 0.1}
