# xuất bản joint_states để quan sát
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# điều khiển trực tiếp bánh trái (rad/s)
left_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_main_wheel_joint
  pid: {p: 10.0, i: 0.1, d: 0.0}   # tinh chỉnh sau nếu cần

# điều khiển trực tiếp bánh phải (rad/s)
right_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_main_wheel_joint
  pid: {p: 10.0, i: 0.1, d: 0.0}
